export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_ALL_DOGS_BY_ID = "GET_ALL_DOGS_BY_ID";
export const CLEAN_DOGS = "CLEAN_DOGS";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const SORTING_ABC = "SORTING_ABC"; 
export const SORTING_BY_WEIGHT = "SORTING_BY_WEIGHT"; 
export const CREATE_DOG = "CREATE_DOG";
export const MOVING_PAGE = "MOVING_PAGE";






